#+TITLE: Druix: Drew's (G)uix

Druix is a GNU Guix Channel, among other things. It's based off of how
I, =drewc=, use Guix both personally and on a business scale.

GNU Guix is a cross-platform package manager and a tool to instantiate and
manage Unix-like operating systems.

Please do NOT promote this repository on any official Guix communication
channels, such as their mailing lists or IRC channel, even in response to
support requests! This is to show respect for the Guix project’s strict policy
against recommending nonfree software, and to avoid any unnecessary hostility.

* Usage

It's a guix channel. Add this to ~~/.config/guix/channels.scm~.

#+begin_src scheme
  (channel
   (name 'druix)
   (url "https://github.com/drewc/druix.git")
   (branch "main"))
#+end_src

For hacking, clone the repo and ~-L~ it.

ie:

#+begin_src shell
guix install -L ~/me/guix/src/druix/ gambit-c-unstable
#+end_src

* dotChannel
#+begin_src scheme :tangle .guix-channel
  (channel
   (version 0)
   (directory "packages")
   (dependencies
    (channel
     (name nonguix)
     (url "https://gitlab.com/nonguix/nonguix"))))
#+end_src
* Package modules

This is what really matters, non? :)

All of the [[info:guix#Package Modules in a Sub-directory][Package Modules]] are in a [[file:packages/README.org][Sub-Directory]].



* Services

-  [[file:doc/Gitea.org][gitea]] :: Gitea - Git with a cup of tea. A painless self-hosted Git service.
  
* NonGuix/NonGNU

    #+begin_quote 
Nonguix is a software repository for the GNU Guix package manager, which
packages some software which cannot be included in the official distribution for
ethical or policy-related reasons.

-- https://gitlab.com/nonguix/nonguix
#+end_quote

Most of my PC's are Thinkpads. Most of them use a "non-free" driver for WiFi,
and they are all Intel or AMD, with firmware updates, etc.

Because of that they require a "non-free" linux kernel and some binary blobs
that Guix refuses to include (for good reason!). My priorities and philosophies
somewhat differ and my freedom is my ability to choose "non-free" hardware :).

Have a look [[file:doc/nonguix.org::*NonGuix/NonGNU in Druix][here]] for details.
