#+TITLE: Druix: Drew's (G)uix

Druix is a distribution of GNU/Linux that's focused on usability. It is based
off of a GNU Guix Channel, amoung other things.

GNU Guix is a cross-platform package manager and a tool to instantiate and
manage Unix-like operating systems.

Please do NOT promote this repository on any official Guix communication
channels, such as their mailing lists or IRC channel, even in response to
support requests! This is to show respect for the Guix project’s strict policy
against recommending nonfree software, and to avoid any unnecessary hostility.

* Usage

Right now it's not (yet) a channel, so clone the repo and ~-L~ it.

ie:

#+begin_src shell
guix install -L ~/me/guix/src/druix/ gambit-c-unstable
#+end_src

* NonGuix/NonGNU

#+begin_quote
Nonguix is a software repository for the GNU Guix package manager, which
packages some software which cannot be included in the official distribution for
ethical or policy-related reasons.

-- https://gitlab.com/nonguix/nonguix
#+end_quote

Most of my PC's are Thinkpads. Most of them use a "non-free" driver for WiFi,
and they are all Intel or AMD, with firmware updates, etc.

Because of that they require a "non-free" linux kernel and some binary blobs
that Guix refuses to include (for good reason!). My priorities and philosophies
somewhat differ and my freedom is my ability to choose "non-free" hardware :).

Have a look [[file:doc/nonguix.org::*NonGuix/NonGNU in Druix][here]] for details.

* Versioning and git


* Scheme: Gambit and Gerbil, "unstable"
